mode: "eval"
output: "results/eval_results"
num_tries: 1
models:
  - "gpt-4o-mini"
  - "gemma-3-27b-it"
  # - "gemini-2.5-flash-lite"
datasets:
  - name: "PBMC3kToy"
    path: "toy_data"
    modality: "single-cell"
    cluster_col: "blind_cluster"
    ground_truth_col: "louvain"
    organism: "Human"
    tissue: "PBMC"
    disease: "Normal"
